"""Bilingual visible labels for the OOXML capability dashboard."""

from __future__ import annotations


DISPLAY = {
    "OOXML Element Capability Dashboard": "OOXML Element Capability Dashboard / OOXML 元素能力看板",
    "Denominators": "Denominators / 分母总账",
    "Claim Summary": "Claim Summary / 声明摘要",
    "Unit Definitions": "Unit Definitions / 单位定义",
    "Capability Levels": "Capability Levels / 能力层级",
    "Semantic Blockers": "Semantic Blockers / 语义阻断项",
    "Families": "Families / 对象家族",
    "Anti-False-Pass Gate Scope": "Anti-False-Pass Gate Scope / 防 false-pass 门禁范围",
    "Campaign Office Boundary Scope": "Campaign Office Boundary Scope / campaign Office 边界范围",
    "Campaign Office Boundary Details": "Campaign Office Boundary Details / campaign Office 边界明细",
    "Source Integrity": "Source Integrity / 来源完整性",
    "Editability": "Editability / 可编辑性",
    "Current Semantic Promotion Gate": "Current Semantic Promotion Gate / 当前语义推进门禁",
    "Semantic Campaign Gap": "Semantic Campaign Gap / 语义推进缺口",
    "Campaign Remaining By Blocker": "Campaign Remaining By Blocker / 按阻断原因的剩余缺口",
    "Campaign Remaining By Family": "Campaign Remaining By Family / 按对象家族的剩余缺口",
    "Campaign Remaining Top QNames": "Campaign Remaining Top QNames / 剩余最多的 QName",
    "Native Office / Public Path Checks": "Native Office / Public Path Checks / Office 与公开路径检查",
    "P80 Family Feasibility": "Former Preserve-Only Family Feasibility / 原 preserve-only 家族可行性",
    "Claim Boundary": "Claim Boundary / 声明边界",
    "Layer": "Layer / 层级",
    "Field": "Field / 字段",
    "Level": "Level / 层级",
    "Unit": "Unit / 单位",
    "Meaning": "Meaning / 含义",
    "中文": "中文",
    "Source": "Source / 来源",
    "Exists": "Exists / 存在",
    "Size": "Size / 大小",
    "SHA-256": "SHA-256",
    "Gate": "Gate / 门禁",
    "Package": "Package / 包",
    "Status": "Status / 状态",
    "Excluded": "Excluded / 已排除",
    "Office result": "Office result / Office 结果",
    "Message": "Message / 消息",
    "Strict claim": "Strict claim / 严格声明",
    "Count": "Count / 数量",
    "Evidence": "Evidence / 证据",
    "Tier": "Tier / 等级",
    "Denominator": "Denominator / 分母",
    "Rows": "Rows / 行数",
    "Rate": "Rate / 比例",
    "Metric": "Metric / 指标",
    "Value": "Value / 值",
    "Blocker": "Blocker / 阻断原因",
    "QName": "QName / XML 名称",
    "Check": "Check / 检查项",
    "Family": "Family / 家族",
    "Total": "Total / 总数",
    "Semantic value available": "Semantic value available / 有语义值",
    "Pending proof": "Pending proof / 待补证明",
    "Explicit unsupported": "Explicit unsupported / 明确不支持",
    "No semantic value": "No semantic value / 无语义值",
    "Resolve fail": "Resolve fail / 解析失败",
    "XML elements": "XML elements / XML 元素",
    "Object candidates": "Object candidates / 对象候选",
    "Readable": "Readable / 可读",
    "Semantic live": "Semantic live / 当前语义可改",
    "Remaining": "Remaining / 剩余",
    "Office pass": "Office pass / Office 通过",
    "Full claim": "Full claim / 全量声明",
    "Surface-editable": "Surface-editable / 安全边界可写",
    "Semantic-editable": "Semantic-editable / 语义可写",
    "Unsupported / not proven": "Unsupported / not proven / 不支持或未证明",
    "Office output files": "Office output files / Office 输出文件",
    "XML element instances": "XML element instances / XML 元素实例",
    "xml_element_instances": "xml_element_instances / XML 元素实例",
    "object_candidates": "object_candidates / 对象候选",
    "readable_inspectable": "readable_inspectable / 可读/可检查",
    "semantic_handle_object_denominator": "semantic_handle_object_denominator / SH 对象分母",
    "opaque_binary_package_dependencies": "opaque_binary_package_dependencies / 不透明包依赖",
    "surface_editable": "surface_editable / 安全边界可写",
    "semantic_editable": "semantic_editable / 语义可写",
    "full_write": "full_write / 完整写入",
    "unsupported_or_not_proven": "unsupported_or_not_proven / 不支持或未证明",
    "office_output_files": "office_output_files / Office 输出文件",
    "allowed": "allowed / 当前允许声明",
    "forbidden": "forbidden / 禁止声明",
    "current": "current / 当前结论",
    "surface_editable_count": "surface_editable_count / 安全边界可写数量",
    "semantic_editable_count": "semantic_editable_count / 语义可写数量",
    "full_claim_proven": "full_claim_proven / 全量声明已证明",
    "semantic_blocker_count": "semantic_blocker_count / 语义阻断数量",
    "anti_false_pass_gate": "anti_false_pass_gate / 防 false-pass 门禁",
    "XML parts parsed": "XML parts parsed / 已解析 XML part",
    "Package parts": "Package parts / 包 part",
    "Relationships": "Relationships / 关系",
    "Distinct QNames": "Distinct QNames / 不同 QName",
    "Readable / inspectable": "Readable / inspectable / 可读/可检查",
    "Former preserve-only": "Former preserve-only / 原 preserve-only",
    "surface-editable frozen denominator": "surface-editable frozen denominator / surface 可编辑冻结分母",
    "semantic-editable live working tree": "semantic-editable live working tree / 当前工作树语义可编辑",
    "semantic-editable remaining": "semantic-editable remaining / 语义可编辑剩余",
    "SH object denominator": "SH object denominator / SH 对象分母",
    "Current SH semantic rows": "Current SH semantic rows / 当前 SH 语义行",
    "P80 semantic promoted": "Campaign semantic promoted / campaign 已推进语义对象",
    "P80 semantic value available": "Campaign semantic value available / campaign 有语义值",
    "P80 semantic value missing": "Campaign semantic value missing / campaign 缺语义值",
    "P80 resolve/parse failure": "Campaign resolve/parse failure / campaign 定位或解析失败",
    "Anti-false-pass gate": "Anti-false-pass gate / 防 false-pass 门禁",
    "Full semantic claim proven": "Full semantic claim proven / 全量语义声明已证明",
    "Campaign denominator": "Campaign denominator / campaign 分母",
    "Campaign semantic-editable": "Campaign semantic-editable / campaign 语义可编辑",
    "Campaign remaining": "Campaign remaining / campaign 剩余",
    "Campaign object-level gap rows": "Campaign object-level gap rows / campaign 逐对象缺口行",
    "Campaign anti-false-pass gate": "Campaign anti-false-pass gate / campaign 防 false-pass 门禁",
    "Campaign full claim proven": "Campaign full claim proven / campaign 全量声明已证明",
    "no_semantic_value": "no_semantic_value / 缺语义值",
    "resolve_failure": "resolve_failure / 定位或解析失败",
    "semantic_value_available_pending_proof": "semantic_value_available_pending_proof / 有语义值但缺完整证明",
    "relationship_identity_like": "relationship_identity_like / 关系或身份标识",
    "binary_payload_reference": "binary_payload_reference / 二进制载荷引用",
    "needs_family_model": "needs_family_model / 需要家族模型",
    "needs_vendor_family_model": "needs_vendor_family_model / 需要厂商家族模型",
    "all_families": "all_families / 全部家族",
    "P80 Office gate pass": "Native Office gate pass / Native Office 门禁通过",
    "P80 Office result files": "Native Office result files / Native Office 结果文件",
    "P80 Office blockers": "Native Office blockers / Native Office 阻断项",
    "Unreadable content": "Unreadable content / 不可读内容",
    "Exact after-value oracle failures": "Exact after-value oracle failures / 写后精确值 oracle 失败",
    "CLI path unchecked": "CLI path unchecked / CLI 路径未检查",
    "MCP path unchecked": "MCP path unchecked / MCP 路径未检查",
    "MCP list_tools": "MCP list_tools / MCP 工具列表",
    "MCP call_tool replay": "MCP call_tool replay / MCP 工具调用 replay",
    "office_extension": "office_extension / Office 扩展",
    "alternate_content": "alternate_content / AlternateContent 分支",
    "custom_xml_schema": "custom_xml_schema / 自定义 XML schema",
    "vml_drawing": "vml_drawing / VML 绘图",
    "math_object": "math_object / OMML 公式",
    "office_chart_extension": "office_chart_extension / Office 图表扩展",
    "legacy_office_drawing": "legacy_office_drawing / 旧式 Office 绘图",
    "wps_extension": "wps_extension / WPS 扩展",
    "chart_drawing": "chart_drawing / 图表绘图",
    "custom_xml_payload": "custom_xml_payload / 自定义 XML 业务 payload",
    "sharepoint_property": "sharepoint_property / SharePoint 属性",
    "vendor_private_extension": "vendor_private_extension / 厂商私有扩展",
    "drawing_extension": "drawing_extension / DrawingML 扩展",
    "office_drawing_sketch_extension": "office_drawing_sketch_extension / Office sketch 绘图扩展",
    "Surface-editable means safe object-bound write, not full semantic understanding.": "Surface-editable means safe object-bound write, not full semantic understanding. / surface 可编辑只代表安全对象边界写入，不代表完整语义理解。",
    "Semantic-editable rows require exact before/requested/after value proof.": "Semantic-editable rows require exact before/requested/after value proof. / 语义可编辑行必须有 before/requested/after 精确值证明。",
    "Full-write is not globally claimed; it must be proven per family and operation.": "Full-write is not globally claimed; it must be proven per family and operation. / full-write 不能全局声明，必须按 family 和 operation 证明。",
    "Package-level pass, aggregate replay, and marker-only mutation cannot be counted as object-level semantic editability.": "Package-level pass, aggregate replay, and marker-only mutation cannot be counted as object-level semantic editability. / 包级通过、聚合 replay、只贴 marker 都不能算逐对象语义编辑。",
}


def display_text(label: str) -> str:
    return DISPLAY.get(label, label)
