#!/usr/bin/env python3
"""Report source files and functions that exceed the repository size guidance.

Guidance (documented in CONTRIBUTING.md): a source module should stay under 300
lines and a function under 50 lines. Oversized units are not automatically a
defect, but each one has to be a recorded exception rather than an accident, so
`--write` regenerates `docs/SIZE-EXCEPTIONS.md` from the current tree and the
lint gate fails while the recorded list is stale.
"""

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXCEPTIONS = ROOT / "docs" / "SIZE-EXCEPTIONS.md"
FILE_LIMIT = 300
FUNCTION_LIMIT = 50
SOURCE_ROOTS = ("src", "scripts", "ooxml_runner", "backend", "mcp", "codegen", "tools")
SKIP_PARTS = {".venv", "build", "dist", "_gen", "__pycache__", "tests", "docs"}


def source_files() -> list[Path]:
    files: list[Path] = []
    for root in SOURCE_ROOTS:
        base = ROOT / root
        if not base.is_dir():
            continue
        for path in sorted(base.rglob("*.py")):
            if SKIP_PARTS & set(path.parts):
                continue
            files.append(path)
    return files


def oversized(
    files: list[Path],
) -> tuple[list[tuple[str, int]], list[tuple[str, int, int]]]:
    big_files: list[tuple[str, int]] = []
    big_functions: list[tuple[str, int, int]] = []
    for path in files:
        text = path.read_text(encoding="utf-8", errors="replace")
        lines = text.count("\n") + 1
        rel = str(path.relative_to(ROOT))
        if lines > FILE_LIMIT:
            big_files.append((rel, lines))
        try:
            tree = ast.parse(text)
        except SyntaxError:
            continue
        for node in ast.walk(tree):
            if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue
            end = getattr(node, "end_lineno", None)
            if end is None:
                continue
            length = end - node.lineno + 1
            if length > FUNCTION_LIMIT:
                big_functions.append((rel, node.lineno, length))
    big_files.sort(key=lambda item: -item[1])
    big_functions.sort(key=lambda item: -item[2])
    return big_files, big_functions


def render(files: list[Path], big_files, big_functions) -> str:
    lines = [
        "# Size exceptions",
        "",
        f"Guidance: a source module stays under {FILE_LIMIT} lines and a function",
        f"under {FUNCTION_LIMIT} lines (see `CONTRIBUTING.md`). This file records the",
        "units that exceed it today, generated by `python3 scripts/size_report.py --write`.",
        "The lint gate fails when this list no longer matches the tree, so an",
        "exception is a decision rather than an oversight.",
        "",
        f"Source files scanned: {len(files)}.",
        "",
        f"## Modules over {FILE_LIMIT} lines",
        "",
    ]
    if big_files:
        lines += ["| Module | Lines |", "| --- | ---: |"]
        lines += [f"| `{name}` | {count} |" for name, count in big_files]
    else:
        lines.append("None.")
    lines += ["", f"## Functions over {FUNCTION_LIMIT} lines", ""]
    if big_functions:
        lines += ["| Function | Line | Length |", "| --- | ---: | ---: |"]
        lines += [
            f"| `{name}:{line}` | {line} | {length} |"
            for name, line, length in big_functions
        ]
    else:
        lines.append("None.")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--write", action="store_true", help="regenerate docs/SIZE-EXCEPTIONS.md"
    )
    parser.add_argument(
        "--check", action="store_true", help="fail when the recorded list is stale"
    )
    args = parser.parse_args()

    files = source_files()
    big_files, big_functions = oversized(files)
    rendered = render(files, big_files, big_functions)

    if args.write:
        EXCEPTIONS.parent.mkdir(parents=True, exist_ok=True)
        EXCEPTIONS.write_text(rendered, encoding="utf-8")
        print(
            f"wrote {EXCEPTIONS.relative_to(ROOT)}: "
            f"{len(big_files)} modules, {len(big_functions)} functions over guidance"
        )
        return 0

    print(
        f"source files: {len(files)}; modules over {FILE_LIMIT}: {len(big_files)}; "
        f"functions over {FUNCTION_LIMIT}: {len(big_functions)}"
    )
    if args.check:
        if not EXCEPTIONS.exists():
            print(
                f"{EXCEPTIONS.relative_to(ROOT)} is missing; run "
                "`python3 scripts/size_report.py --write`",
                file=sys.stderr,
            )
            return 1
        recorded = EXCEPTIONS.read_text(encoding="utf-8").strip()
        if recorded != rendered.strip():
            print(
                "size exceptions are stale: the tree changed since "
                f"{EXCEPTIONS.relative_to(ROOT)} was generated; rerun with --write "
                "and review the new entries",
                file=sys.stderr,
            )
            return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
